packages:
  - .

enablePrePostScripts: true

allowBuilds:
  sharp: true
  '@vercel/git-hooks': false
  esbuild: false
  unrs-resolver: false

patchedDependencies:
  '@payloadcms/plugin-ecommerce@3.85.2': 'patches/@payloadcms__plugin-ecommerce@3.85.2.patch'

# Network
fetchTimeout: 1800000
fetchRetries: 10
fetchRetryFactor: 2
fetchRetryMintimeout: 60000
fetchRetryMaxtimeout: 600000
networkConcurrency: 1
strictSsl: true
